version: "3"
services:
  posbackend_apigateway:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_apigateway
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    ports:
      - "10000:80"
      - "443:80"
    volumes:
      - ./microservices/shared/environment/.env.api_gateway:/var/www/html/.env
      - ./microservices/shared/setup.sh:/var/www/html/setup.sh
      - ./microservices/shared/config/api_gateway.php:/var/www/html/config/api_gateway.php
      - ./microservices/shared/BaseRepository:/var/www/html/app/BaseRepository
      - ./microservices/api_gateway:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/api_gateway.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend

  posbackend_person:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_person
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    expose:
      - "80"
    volumes:
      - ./microservices/shared/environment/.env.person:/var/www/html/.env
      - ./microservices/shared/setup.sh:/var/www/html/setup.sh
      - ./microservices/shared/config/api_gateway.php:/var/www/html/config/api_gateway.php
      - ./microservices/shared/BaseRepository:/var/www/html/app/BaseRepository
      - ./microservices/person:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/person.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql

  posbackend_localization:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_localization
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    expose:
      - "80"
    volumes:
      - ./microservices/shared/environment/.env.localization:/var/www/html/.env
      - ./microservices/shared/setup.sh:/var/www/html/setup.sh
      - ./microservices/shared/config/api_gateway.php:/var/www/html/config/api_gateway.php
      - ./microservices/shared/BaseRepository:/var/www/html/app/BaseRepository
      - ./microservices/localization:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/localization.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql

  posbackend_job:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_job
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    expose:
      - "80"
    volumes:
      - ./microservices/shared/environment/.env.job:/var/www/html/.env
      - ./microservices/shared/setup.sh:/var/www/html/setup.sh
      - ./microservices/shared/config/api_gateway.php:/var/www/html/config/api_gateway.php
      - ./microservices/shared/BaseRepository:/var/www/html/app/BaseRepository
      - ./microservices/job:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/job.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql

  posbackend_schedule:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_schedule
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    expose:
      - "80"
    volumes:
      - ./microservices/shared/environment/.env.schedule:/var/www/html/.env
      - ./microservices/shared/setup.sh:/var/www/html/setup.sh
      - ./microservices/shared/config/api_gateway.php:/var/www/html/config/api_gateway.php
      - ./microservices/shared/BaseRepository:/var/www/html/app/BaseRepository
      - ./microservices/schedule:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/schedule.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql
  
  posbackend_attendance:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_attendance
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    expose:
      - "80"
    volumes:
      - ./microservices/shared/environment/.env.attendance:/var/www/html/.env
      - ./microservices/shared/setup.sh:/var/www/html/setup.sh
      - ./microservices/shared/config/api_gateway.php:/var/www/html/config/api_gateway.php
      - ./microservices/shared/BaseRepository:/var/www/html/app/BaseRepository
      - ./microservices/attendance:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/attendance.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql

  pospostgresql:
    image: postgres:14.3
    container_name: pospostgresql
    user: 0:0
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - netork_pos_backend

  pospgadmin:
    image: dpage/pgadmin4
    container_name: pospgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "jonathan.estefani@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - pospostgresql
    networks:
      - netork_pos_backend

networks:
  netork_pos_backend:
    driver: bridge
