version: "3"
services:
  posbackend_customers:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: posbackend_customers
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    ports:
      - "8000:80"
    volumes:
      - ./customers:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql

  pospostgresql:
    image: postgres
    container_name: pospostgresql
    user: 0:0
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - netork_pos_backend

  pospgadmin:
    image: dpage/pgadmin4
    container_name: pospgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "jonathan.estefani@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - pospostgresql
    networks:
      - netork_pos_backend

networks:
  netork_pos_backend:
    driver: bridge
