version: "3"
services:
  posbackend_apigateway:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_apigateway
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    ports:
      - "10000:80"
    volumes:
      - ./api_gateway:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/api_gateway.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend

  posbackend_customers:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_customers
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    ports:
      - "10001:80"
    volumes:
      - ./customers:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/customers.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql

  posbackend_localization:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_localization
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    ports:
      - "10002:80"
    volumes:
      - ./localization:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/localization.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql

  posbackend_users:
    image: tangramor/nginx-php8-fpm
    user: 0:0
    container_name: posbackend_users
    environment:
      TZ: "America/Sao_Paulo"
      WEBROOT: "/var/www/html"
    ports:
      - "10003:80"
    volumes:
      - ./users:/var/www/html
      - ./docker/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/etc/php/php.ini:/etc/php8/php.ini
      - ./docker/etc/nginx/conf.d/users.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netork_pos_backend
    depends_on:
      - pospostgresql
    links:
      - pospostgresql

  pospostgresql:
    image: postgres:14.3
    container_name: pospostgresql
    user: 0:0
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - netork_pos_backend

  pospgadmin:
    image: dpage/pgadmin4
    container_name: pospgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "jonathan.estefani@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - pospostgresql
    networks:
      - netork_pos_backend

networks:
  netork_pos_backend:
    driver: bridge
